apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: noahmcgill/api:v1
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgresql-password
        - name: DB_NAME
          value: "k8s"
        - name: DB_PORT
          value: "5432"
        - name: DB_HOST
          value: pgpool-svc
