apiVersion: v1
kind: Service
metadata:
  name: postgres-headless-svc
  labels:
    app: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5432
    name: postgresql
    targetPort: postgresql
    protocol: TCP
  selector:
    app: postgres
